server:
  port: 8081

spring:
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  database:
    driverClassName: org.postgresql.Driver

resources:
  avatar:
#    url: /static/images/
    url: /tmp/avatar/